-- 1. Profiles (Extends auth.users)
create table public.profiles (
  id uuid references auth.users not null primary key,
  user_name text,
  email text,
  role text check (role in ('admin', 'driver', 'passenger')) default 'passenger',
  created_at timestamptz default now()
);

-- Enable RLS
alter table public.profiles enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can update own profile"
  on profiles for update
  using ( auth.uid() = id );

-- Trigger to create profile after signup
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, user_name, role)
  values (
    new.id, 
    new.email, 
    coalesce(new.raw_user_meta_data->>'full_name', new.email),
    coalesce(new.raw_user_meta_data->>'role', 'passenger')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Vehicles
create table public.vehicles (
  id bigint generated by default as identity primary key,
  plate_number text not null unique,
  make text not null,
  model text not null,
  year integer not null,
  capacity integer not null,
  status text check (status in ('active', 'maintenance', 'inactive')) default 'active',
  driver_id uuid references public.profiles(id),
  proposed_by_driver_id uuid references public.profiles(id),
  approved boolean default false,
  approved_at timestamptz,
  approved_by_admin_id uuid references public.profiles(id),
  created_at timestamptz default now()
);

alter table public.vehicles enable row level security;

-- Vehicles Policies
create policy "Vehicles are viewable by everyone" 
  on vehicles for select using (true);

create policy "Drivers can insert their own vehicles" 
  on vehicles for insert 
  with check ( auth.uid() = proposed_by_driver_id );

-- 3. Routes
create table public.routes (
  id bigint generated by default as identity primary key,
  route_name text not null,
  start_location_name text not null,
  start_location_lat double precision not null,
  start_location_lng double precision not null,
  end_location_name text not null,
  end_location_lat double precision not null,
  end_location_lng double precision not null,
  distance double precision not null,
  estimated_time integer not null, -- minutes
  approved boolean default false,
  created_at timestamptz default now(),
  approved_at timestamptz,
  approved_by_admin_id uuid references public.profiles(id),
  proposed_by_driver_id uuid references public.profiles(id)
);

alter table public.routes enable row level security;

create policy "Routes are viewable by everyone" on routes for select using (true);
create policy "Drivers can propose routes" on routes for insert with check (auth.uid() = proposed_by_driver_id);

-- 4. Trips
create table public.trips (
  id bigint generated by default as identity primary key,
  route_id bigint references public.routes(id) not null,
  vehicle_id bigint references public.vehicles(id) not null,
  driver_id uuid references public.profiles(id),
  departure_time timestamptz not null,
  arrival_time timestamptz not null,
  status text check (status in ('scheduled', 'on_route', 'completed', 'cancelled')) default 'scheduled',
  fare double precision not null,
  available_seats integer not null,
  created_at timestamptz default now()
);

alter table public.trips enable row level security;

create policy "Trips are viewable by everyone" on trips for select using (true);
create policy "Drivers can create trips" on trips for insert with check (auth.uid() = driver_id);
create policy "Drivers can update their own trips" on trips for update using (auth.uid() = driver_id);

-- 5. Trip Locations
create table public.trip_locations (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) on delete cascade not null,
  latitude double precision not null,
  longitude double precision not null,
  timestamp timestamptz default now()
);

alter table public.trip_locations enable row level security;

create policy "Locations viewable by everyone" on trip_locations for select using (true);
create policy "Drivers can insert locations for their trips" 
  on trip_locations for insert 
  with check (
    exists (
      select 1 from trips 
      where id = trip_locations.trip_id
      and driver_id = auth.uid()
    )
  );

-- 6. Bookings
create table public.bookings (
  id bigint generated by default as identity primary key,
  trip_id bigint references public.trips(id) not null,
  passenger_id uuid references public.profiles(id) not null,
  seat_number integer not null,
  booking_date timestamptz default now(),
  status text check (status in ('confirmed', 'pending', 'cancelled')) default 'confirmed',
  total_amount double precision not null,
  pickup_location_lat double precision,
  pickup_location_lng double precision,
  dropoff_location_lat double precision,
  dropoff_location_lng double precision
);

alter table public.bookings enable row level security;

create policy "Users can see own bookings" on bookings for select using (auth.uid() = passenger_id);
create policy "Drivers see bookings for their trips" on bookings for select using (
  exists (
    select 1 from trips
    where id = bookings.trip_id
    and driver_id = auth.uid()
  )
);
create policy "Passengers can create bookings" on bookings for insert with check (auth.uid() = passenger_id);

-- Admin Policies (Full Access)
-- Note: This assumes profiles table is populated correctly.
create policy "Admins can do everything on profiles" on profiles using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );
create policy "Admins can do everything on vehicles" on vehicles using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );
create policy "Admins can do everything on routes" on routes using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );
create policy "Admins can do everything on trips" on trips using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );
create policy "Admins can do everything on trip_locations" on trip_locations using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );
create policy "Admins can do everything on bookings" on bookings using ( exists (select 1 from profiles where id = auth.uid() and role = 'admin') );

